apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1 # one replica is needed since only one instance of a database is needed
  selector:
    matchLabels:
      name: postgres-pod
      app: demo-voting-app
  
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: demo-voting-app
    spec:
      containers:
        - name: postgres-container
          image: postgres:9.4

          ports:
            - containerPort: 5432